### PR TITLE
Library jpa aa

### PR DESCRIPTION
**Pull request by lexieAA**
Library Service should be able to update a library branch and the number of book copies. I have it also be able to read the branches and book copies.

### CODE REVIEW

**Comment by jalvesteffer** [comment]
The pull request is showing my old code from 4 days ago.  Did you pull the right files?  I don't see any of your code.

**Review by Matt-McIntyre — COMMENTED** [review]
Are these DAO's supposed to be new JPA versions?

**Review by Matt-McIntyre — APPROVED** [review]
approved

**Comment by jalvesteffer** [comment]
I think the wrong version of code is in the pull request.  I saw old code
when I reviewed it.

**Comment by lexieAA** [comment]
Your right let me fix that

**Comment by lexieAA** [comment]
okay what do you think now

**Comment by jalvesteffer** [comment]
If this is still open, can you resend a request to me?  I think something went wrong on my end.  The changes are my old files, not yours.

**Pull request closed without merging**
